default[:php][:user]        = "root"
default[:php][:group]       = "root"
default[:php][:source_dir]  = "/usr/src"
default[:php][:config_dir]  = "/etc"
default[:php][:log_dir]     = "/var/log"
default[:php][:deb_file]    = "php_5.5.5-1_amd64.deb"
default[:php][:doc_root]    = "/vagrant"
default[:php][:extensions_dir] = "/usr/lib/php/extensions"
